version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
environment:
  github_api_key:
    secure: HQRCTpyiWV9bLFW8sJRCZI1YwijEW8bd80nIxnj2IxZPnUiSSKEoupidNHCzJRtx
install:
  - git submodule update --init --recursive
build_script:
- cmd: >-
    mkdir build

    cd build
    
    cmake .. -DCMAKE_PREFIX_PATH=C:/Qt/5.7/msvc2015/lib/cmake

    cmake --build . --config Release --target package
deploy:
- provider: GitHub
  auth_token:
    secure: HQRCTpyiWV9bLFW8sJRCZI1YwijEW8bd80nIxnj2IxZPnUiSSKEoupidNHCzJRtx
